# ----------------------- 其它全局配置 -----------------
title: 小刘同学
description: 小刘同学的个人博客
author: jack·liu
# 头像
avatar: /static/img/avatar.png
# logo
logo: /static/img/avatar.png

# ----------------------- 服务器配置 -----------------
# 服务器根目录
source: .
# 本地运行时生成的网站目录
destination: ./_site
# 布局页面的路径
layouts_dir: _layouts
# 本地启服务的端口号
port: 4001
# 本地启服务器的 ip
host: 127.0.0.1
baseurl: ""
url: ""

# ----------------------- markdown 转换 & 语法高亮 -----------------
markdown: kramdown
kramdown:
    math_engine: mathjax # 非安装包，需要引入 js 参考 https://www.jianshu.com/p/aa359b3aef0c
    syntax_highlighter: rouge

# ----------------------- 插件配置 -----------------
plugins: [jekyll-paginate, jekyll-watch] # Jekyll < 3.5.0 版本使用的字段是 gems: [jekyll-paginate]

# ----------------------- 输出配置 -----------------
# 博客的 URL 地址，是个枚举值
permalink: date # /:categories/:year/:month/:day/:title.html
# 分页中每页显示 10 条博客
paginate: 2
paginate_path: "/page:num/"
